### ISSUE TITLE
Parabel training issue

### ISSUE THREAD

**Issue by 1074051286** [yuzhimanhua/MAPLE#3]
Dear Yu：
      When I training Parabel, it occurs this Problem：
      Traceback (most recent call last):
  File "patk.py", line 134, in <module>
    p1, p3, p5, n3, n5 = get_p_1(preds, targets, mlb), get_p_3(preds, targets, mlb), get_p_5(preds, targets, mlb), \
  File "patk.py", line 35, in get_precision
    prediction = mlb.transform(prediction[:, :top])
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by yuzhimanhua** [comment]
Hello,

I guess it is because we are using different versions of scikit-learn. Could you please use scikit-learn 0.22.0?

If it does not work, could you also update numpy and scipy according to the following file? Thanks!
https://github.com/yuzhimanhua/MAPLE/blob/master/Transformer/requirements.txt

**Comment by 1074051286** [comment]
Thanks for your guide！I’ll try it :)




1074051286
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuzhimanhua/MAPLE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月28日(星期天) 晚上9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuzhimanhua/MAPLE] Parabel training issue (Issue #3)





 
Hello,
 
I guess it is because we are using different versions of scikit-learn. Could you please use scikit-learn 0.22.0?
 
If it does not work, could you also update numpy and scipy according to the following file? Thanks!
 https://github.com/yuzhimanhua/MAPLE/blob/master/Transformer/requirements.txt

**Comment by 1074051286** [comment]
Dear Yu:
         The problem proposed in the last mail has been solved by updating the glibc version. But I still have another problem when traning Transformer. After reading the scripts in ./Transformer/run.sh ./Transformer/run_models.sh and files in&nbsp; ./Transformer/data, I find these options only focus on Art and lost other fields' data. Since our lab mainly focus on geoscience, I think maybe I need the Geology/Geography/Chemistry and other fields data under ./Trasformer/data. Could you please offer that？That's important to my work.Thanks :)



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuzhimanhua/MAPLE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月28日(星期天) 晚上9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuzhimanhua/MAPLE] Parabel training issue (Issue #3)





 
Hello,
 
I guess it is because we are using different versions of scikit-learn. Could you please use scikit-learn 0.22.0?
 
If it does not work, could you also update numpy and scipy according to the following file? Thanks!
 https://github.com/yuzhimanhua/MAPLE/blob/master/Transformer/requirements.txt

**Comment by yuzhimanhua** [comment]
Hello,

Sorry, I did not get the meaning of "lost other fields' data". After you change ```DATASET``` from "Art" to "Geography" in https://github.com/yuzhimanhua/MAPLE/blob/master/Transformer/run.sh#L3 and run ```run.sh```, what errors do you hit? 

I expect the following line: https://github.com/yuzhimanhua/MAPLE/blob/master/Transformer/run.sh#L6 will automatically prepare the data for Transformer training if you change ```DATASET``` to your desired field. Thanks!

**Comment by 1074051286** [comment]
I get you point. I originally thought these data should be provided in advance. Thanks！




1074051286
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuzhimanhua/MAPLE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 中午12:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuzhimanhua/MAPLE] Parabel training issue (Issue #3)





 
Hello,
 
Sorry, I did not get the meaning of "lost other fields' data". After you change DATASET from "Art" to "Geography" in https://github.com/yuzhimanhua/MAPLE/blob/master/Transformer/run.sh#L3 and run run.sh, what errors do you hit?
 
I expect the following line: https://github.com/yuzhimanhua/MAPLE/blob/master/Transformer/run.sh#L6 will automatically prepare the data for Transformer training if you change DATASET to your desired field. Thanks!
